services:
  core-db:
    build: .
    container_name: cat-core-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: core_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      cat-network: 192.168.1.100 # You may need to change this IP address
        

volumes:
  postgres_data:
    driver: local

networks:
  cat-network:
    external: true